#!/usr/bin/env bash

# Create cmdline.txt file
cat <<EOF > "${work_dir}"/boot/firmware/cmdline.txt
console=serial0,115200 console=tty1 root=PARTUUID=$root_partuuid rootfstype=$rootfstype fsck.repair=yes rootwait net.ifnames=0
EOF

# Copy a default config, with everything commented out so people find it when
# they go to add something when they are following instructions on a website.
cp ./bsp/firmware/rpi/config.txt "${work_dir}"/boot/firmware/config.txt
echo -e "DO NOT EDIT THIS FILE\n\nThe file you are looking for has moved to /boot/firmware/config.txt" > "${work_dir}"/boot/config.txt
